name = "Rust CLI template"
description = "A very opinionated CLI template for Rust projects "
kickstart_version = 1
url = "https://github.com/hmuendel/rust-cli-template"
authors = [
    "Hans Mündelein <hans@muendelein.me>"
]
ignore = [
    ".gitignore",
    "README.md",
    "LICENSE",
]

cleanup = [
    {name = "debugging", value = "None", paths = ["{{project_name}}/.vimspector.json"]},
    {name = "example_lib", value = false, paths = [
    "{{project_name}}/{%- if lib_name %}{{ lib_name }}{% else %}{{ project_name }}_lib{% endif -%}",
    ]},
    {name = "toolchain", value = "stable", paths = [
    "{{project_name}}/{%- if lib_name %}{{ lib_name }}{% else %}{{ project_name }}_lib{% endif -%}/benches",
    ]},
    {name = "benches", value = false, paths = [
    "{{project_name}}/{%- if lib_name %}{{ lib_name }}{% else %}{{ project_name }}_lib{% endif -%}/benches",
    ]},
    {name = "license", value = "None", paths = [
    "{{project_name}}/LICENSE", 
    "{{project_name}}/{%- if bin_name %}{{ bin_name }}{% else %}{{ project_name }}{% endif -%}/LICENSE",
    "{{project_name}}/{%- if lib_name %}{{ lib_name }}{% else %}{{ project_name }}_lib{% endif -%}/LICENSE",
    ]},
]

[[variables]]
name = "project_name"
default = "cli"
prompt = "What's the name of the project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "bin_name"
default = ""
prompt = "Name of the binary, if not set uses the project name"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "lib_name"
default = ""
prompt = "Name of the library, if not set uses the project name with _lib suffix"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "description"
default = "A CLI application"
prompt = "A short description of the app?"

[[variables]]
name = "long_description"
default = "TODO: Finish writing detailed documentation"
prompt = "A detailed documentation of your app?"

[[variables]]
name = "author"
default = "No One"
prompt = "What is your name?"

[[variables]]
name = "email"
default = "no@one.test"
prompt = "What is your email?"

[[variables]]
name = "license"
default = "MIT"
prompt = "Which open-source license do you want to use?"
choices = [
    "MIT",
    "BSD",
    "GPLv3",
    "None",
]

[[variables]]
name = "example_lib"
default = true
prompt = "Create a working example lib, that show how the cli is wired and with example tests and docs. It is recommended to nudge oneself to create nice libs."

[[variables]]
name = "toolchain"
default = "nightly"
prompt = "Which debugging toolchain to use for the project, nightly is required for benchmarks"
choices = [
    "nightly",
    "stable",
]
only_if = { name = "example_lib", value = true }

[[variables]]
name = "benches"
default = true
prompt = "Do you want to have the benchmarks for the example lib created."
only_if= { name = "toolchain", value = "nightly" }

[[variables]]
name = "debugging"
default = "Vimspector"
prompt = "Which debugging setup do you want to use?"
choices = [
    "Vimspector",
    "None",
]

[[variables]]
name = "autotag"
default = true
prompt = "Do you want you git repo tagged during build with the cargo version if this tag does not exist?"

